dist: trusty
language: python
python:
    - "2.7"
install: pip install colorama
addons:
    apt:
        packages:
            - dejagnu
            - git
script:
    # Set terminal width. See https://github.com/travis-ci/travis-ci/issues/5407
    - stty cols 168
    - python setup.py build
    - cd testsuite
    - PYTHON=python runtest --debug
