set timeout 10

# regexp for the issue id
set Id {[0-9a-f]{64}}
# regexp that match any number of consecutive ANSI color escape sequences from colorama
set C {(?:\e\[[0-9;]*m)*}

set test "version"
spawn $PYTHON $GI
expect {
    -re "Gitissius v0.1.6.*"	{ pass $test }
    timeout { fail "$test: timeout" }
    eof { fail "$test: EOF" }
}

set iss(title)      {this is the issue title}
set iss(severity)   {low}
set iss(type)       {bug}
set iss(author)     {}
set iss(assign)     {}
set iss(status)     {new}
set iss(desc1)      {this is the first line of the issue description}
set iss(desc2)      {this is the second line of the issue description}

set test "add issue"
spawn $PYTHON $GI add
expect {
    -re {Title \(.*\): } { send "$iss(title)\n"; exp_continue }
    -ex {Type (bug) [b/f]: }
        { send "[string index $iss(type) 0]\n"; exp_continue }
    -ex {Severity (low) [h/m/l]: }
        { send "[string index $iss(severity) 0]\n"; exp_continue }
    -re {Reported From \(.*\): }	{ send "$iss(author)\n"; exp_continue }
    -re {Assigned To \(None\): }	{ send "$iss(assign)\n"; exp_continue }
    -ex {Status (new) [a/n/c/i]: }
        { send "[string index $iss(status) 0]\n"; exp_continue }
    -ex {Description (End with a line containing only '.'): }
        { send "$iss(desc1)\n$iss(desc2)\n.\n"; exp_continue }
    -ex {Create issue (y)? }	{ send "\n"; exp_continue }
    -re "Created issue: ($Id)"	{
        set issue_id $expect_out(1,string)
        pass $test
    }

    timeout { fail "$test: timeout" }
    eof { fail "$test: EOF" }
    default { fail $test }
}

set iss(author)     "$git_user_name <$git_user_email>"
set iss(assign)     None

set issue_template "^${C}Id$C:$C $C$issue_id$C\r
${C}Title$C:$C $C$iss(title)$C\r
${C}Type$C:$C $C[string totitle $iss(type)]$C\r
${C}Severity$C:$C $C[string totitle $iss(severity)]$C\r
${C}Reported From$C:$C ${C}$iss(author)$C\r
${C}Assigned To$C:$C ${C}$iss(assign)$C\r
${C}Created On$C:$C ${C}.*$C\r
${C}Updated On$C:$C ${C}.*$C\r
${C}Status$C:$C $C[string totitle $iss(status)]$C\r
${C}Description$C:$C\r
  $C$iss(desc1)$C\r
  $C$iss(desc2)$C\r
"

set test "show issue"
if {![info exists issue_id]} {
    unresolved $test
} else {
    spawn $PYTHON $GI show $issue_id
    expect {
        -re "$issue_template" {pass $test}

        timeout { fail "$test: timeout" }
        eof { fail "$test: EOF" }
        default { fail $test }
    }
    unset issue_id
}
