
set commands "
close      comment    delete     edit       list       myissues   new
pull       push       show       update
"

foreach c $commands {
    set test "$c --help"
    spawn $PYTHON $GI $c --help

    expect {
        -re "Usage: gitissius.py $c\(\r| .*\r\)
.*\r
Options:\r
  -h, --help\\s+show this help message and exit\r
"       {
            if {[set status [exp_zero_exit_status]] ne {}} {
                fail "$test $status"
            } else {
                pass $test
            }
        }

        timeout     { fail "$test: timeout" }
        eof         { fail "$test: EOF [exp_zero_exit_status]" }
    }
}
