##############################################################################

array unset iss
array set iss {
    title           {this is the issue title. It is so long that it will be trimmed by `git issius list`}
    severity        {high}
    type            {bug}
    reported_from   {Donald Duck <donald@example.com}
    assigned_to     {Micky Mouse <micky.mouse@example.com>}
    status          {assigned}
    desc1           {this is the first line of the issue description}
    desc2           {this is the second line of the issue description}
}

set test "prepare issue 1 (add)"
spawn $PYTHON $GI add
set iss(id) [edit_or_add_issue $test iss]

##############################################################################

array unset show
array set show [array get show_default]
array set show [subst {
    id              "$iss(id)"
    title           "$iss(title)"
    severity        "$iss(severity)"
    type            "$iss(type)"
    reported_from   "$iss(reported_from)"
    assigned_to     "$iss(assigned_to)"
    status          "$iss(status)"
    desc1           "$iss(desc1)"
    desc2           "$iss(desc2)"
}]

set test "prepare issue 1 (show)"
spawn $PYTHON $GI show $show(id)
show_issue $test show false

##############################################################################

array unset iss2
array set iss2 {
    title           {this is the second issue}
    severity        {medium}
    type            {feature}
    reported_from   {}
    assigned_to     {}
    status          {}
    desc1           {this is the first line of the description of the second issue}
    desc2           {this is the second line of the description of the second issue}
}

# Sleep one sec to ensure that iss and iss2 have different created_on and
# updated_on values
after 1000

set test "prepare issue 2 (add)"
spawn $PYTHON $GI add
set iss2(id) [edit_or_add_issue $test iss2]

##############################################################################

array unset show2
array set show2 [array get show_default]
array set show2 [subst {
    id               "$iss2(id)"
    title            "$iss2(title)"
    severity         "$iss2(severity)"
    type             "$iss2(type)"
    desc1            "$iss2(desc1)"
    desc2            "$iss2(desc2)"
}]

set test "prepare issue 2 (show)"
spawn $PYTHON $GI show $show2(id)
show_issue $test show2 false

##############################################################################

set filter_by "
assigned_to assigned_to__exact assigned_to__not assigned_to__startwith
created_on created_on__exact created_on__not created_on__startswith
id id__exact id__not id__startswith
reported_from reported_from__exact reported_from__not reported_from__startswith
status status__exact status__not status__startswith title
title__exact title__not title__startswith type
type__exact type__not type__startswith
updated_on updated_on__exact updated_on__not updated_on__startswith
"

foreach f $filter_by {
    set test "list --filter=$f"

    if {$show(id) eq {} || $show2(id) eq {}} {
        unresolved $test
        continue
    }

    # The expected show array is either show or show2 depending on the filter
    # ending.
    if {[string first __not $f] == -1 } {
        array set expected [array get show]
    } else {
        array set expected [array get show2]
    }
#    puts "$test expected [array get expected]"

    # Map filter names to show array names
    regsub "__.*$" $f {} tag

    # launch `git issius list` command and check output 
    set show_dict [dict create]
    dict append show_dict $expected(id) [dict create {*}[array get expected]]
#    puts "$test tag $tag show_dict $show_dict"
    spawn $PYTHON $GI list --filter=$f:$show($tag)
    list_issues $test $show_dict 1
}

##############################################################################

set test "list --filter=id (substring)"
if {$show(id) eq {}} {
    unresolved $test
} else {
    set show_dict [dict create]
    dict append show_dict $show(id) [dict create {*}[array get show]]
    spawn $PYTHON $GI list --filter=id:[string range $show(id) 10 20]
    list_issues $test $show_dict 1
}

##############################################################################

set sorted_ids [lsort "$show(id)    $show2(id)"]
set sort_order {
    assigned_to     "$show2(id)   $show(id)"
    created_on      "$show(id)    $show2(id)"
    id              $sorted_ids
    reported_from   "$show(id)    $show2(id)"
    status          "$show(id)    $show2(id)"
    title           "$show(id)    $show2(id)"
    type            "$show(id)    $show2(id)"
    updated_on      "$show(id)    $show2(id)"
}

foreach {order id_order} $sort_order {
    set test "list --sort=$order"

    if {$show(id) eq {} || $show2(id) eq {}} {
        unresolved $test
        continue
    }

    set show_dict [dict create]
    dict append show_dict $show(id) [dict create {*}[array get show]]
    dict append show_dict $show2(id) [dict create {*}[array get show2]]

    set id_order [subst $id_order]

    spawn $PYTHON $GI list --sort=$order
    list_issues $test $show_dict 2 $id_order
}

##############################################################################

set test "close issue"
if {$show(id) eq {}} {
    unresolved $test
} else {
    spawn $PYTHON $GI close $show(id)
    if {[close_issue $test show] eq $show(id)} {
        set iss(status)    {closed}
        set show(status)   $iss(status)
    }
}

#############################################################################

set test "list (closed issue)"
# closed issues aren't listed by default
if {$show(id) eq {} || $show2(id) eq {}} {
    unresolved $test
} else {
    set show_dict [dict create]
    dict append show_dict $show2(id) [dict create {*}[array get show2]]
    spawn $PYTHON $GI list
    list_issues $test $show_dict 1
}

#############################################################################

set test "list --all (closed issue)"
# `list --all` lists closed issues too
if {$show(id) eq {} || $show2(id) eq {}} {
    unresolved $test
} else {
    set show_dict [dict create]
    dict append show_dict $show(id) [dict create {*}[array get show]]
    dict append show_dict $show2(id) [dict create {*}[array get show2]]
    spawn $PYTHON $GI list --all
    list_issues $test $show_dict 2
}

#############################################################################

set test "edit issue (change status to invalid)"
if {$show(id) eq {}} {
    unresolved $test
} else {
    set iss(status)     {invalid}
    spawn $PYTHON $GI edit $show(id)
    if {[edit_or_add_issue $test iss show] eq $iss(id)} {
        set show(status)   $iss(status)
    }
}

#############################################################################

set test "list (invalid issue)"
# invalid issues aren't listed by default
if {$show(id) eq {} || $show2(id) eq {}} {
    unresolved $test
} else {
    set show_dict [dict create]
    dict append show_dict $show2(id) [dict create {*}[array get show2]]
    spawn $PYTHON $GI list
    list_issues $test $show_dict 1
}

#############################################################################

set test "list --all (invalid issue)"
# `list --all` lists invalid issues too
if {$show(id) eq {} || $show2(id) eq {}} {
    unresolved $test
} else {
    set show_dict [dict create]
    dict append show_dict $show(id) [dict create {*}[array get show]]
    dict append show_dict $show2(id) [dict create {*}[array get show2]]
    spawn $PYTHON $GI list --all
    list_issues $test $show_dict 2
}
